<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cari_fr-icon</name>
   <tag></tag>
   <elementGuidId>9b252573-84b9-40c4-8a44-be3919b289d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/main/div/div/div/div/div/nav/div/div[2]/div[2]/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Masuk&quot;] > span.fr-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>caaaf1b4-b0d2-47ce-a1b1-8eff0d2ac27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr-icon</value>
      <webElementGuid>4178ed62-5e11-4603-b982-d453cd12042e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5c8fafc5-deea-49c9-b3f4-2bc80d3c1b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>09e62d42-c55c-4c08-a544-378f9d0a432a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6f1efc7-08c1-4a40-8f58-c3e25f882439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;fr-layer-item content&quot;]/div[1]/div[2]/div[1]/main[1]/div[1]/div[@class=&quot;fr-pc-global-nav a11y-focus-section&quot;]/div[@class=&quot;sticky-outer-wrapper fr-global-nav-toolbar&quot;]/div[@class=&quot;sticky-inner-wrapper&quot;]/div[@class=&quot;fr-layer-item&quot;]/nav[@class=&quot;fr-global-nav contained _5QtkxKb0d2qo8xrZ7TTDZ&quot;]/div[@class=&quot;_34g1A1QdX1f-dwK4D1gtEI&quot;]/div[@class=&quot;SDW2K6S-OepeyEDiF6aWR&quot;]/div[2]/div[@class=&quot;fr-header-button account&quot;]/a[1]/span[@class=&quot;fr-icon&quot;]</value>
      <webElementGuid>a46fc6da-8d66-4007-99e1-04fa3aef6305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/main/div/div/div/div/div/nav/div/div[2]/div[2]/div/a/span</value>
      <webElementGuid>356d0cd7-9943-42e7-a92f-215307d49d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::span[1]</value>
      <webElementGuid>92b2886f-013a-47c4-898f-87e2e4c62bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAYI'])[1]/following::span[3]</value>
      <webElementGuid>c07364cb-637c-47ea-83ce-9041e03e3503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATASAN'])[1]/preceding::span[3]</value>
      <webElementGuid>05918a3b-c472-47a0-b5a0-e8dd9bc5fcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koleksi Atasan'])[1]/preceding::span[7]</value>
      <webElementGuid>cc524845-07db-4041-a0b3-a39d741d550c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a/span</value>
      <webElementGuid>a6db9e5a-a2ad-4f9c-80d2-8cf3a98eb501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
