<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_5</name>
   <tag></tag>
   <elementGuidId>d8b7183e-761f-470e-b1ed-388cd1d35639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Keranjang&quot;] > span.fr-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/main/div/div/div/div/div/nav/div/div[2]/div[4]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>49c9d573-523b-4180-9e5d-fc762b63bcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr-icon</value>
      <webElementGuid>6ce86bb3-1e5b-4c87-a316-a4b221e6f6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>66b93d07-c0f9-408f-bce9-353eaf2c8448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Keranjang</value>
      <webElementGuid>bf183d7b-853e-42fd-bc8b-642b81fe70c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e1a4ccfe-2e9c-419e-ba0d-9f89e4884702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>742a06d4-09eb-4ec2-a431-45c93e75f475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;fr-layer-item content&quot;]/div[1]/div[1]/div[1]/main[1]/div[1]/div[@class=&quot;fr-pc-global-nav a11y-focus-section&quot;]/div[@class=&quot;sticky-outer-wrapper fr-global-nav-toolbar&quot;]/div[@class=&quot;sticky-inner-wrapper&quot;]/div[@class=&quot;fr-layer-item&quot;]/nav[@class=&quot;fr-global-nav contained _5QtkxKb0d2qo8xrZ7TTDZ&quot;]/div[@class=&quot;_34g1A1QdX1f-dwK4D1gtEI&quot;]/div[@class=&quot;SDW2K6S-OepeyEDiF6aWR&quot;]/div[@class=&quot;fr-header-button&quot;]/a[1]/span[@class=&quot;fr-icon&quot;]</value>
      <webElementGuid>4bf3c96e-3ca9-4bb2-8d7a-c79240d22636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/main/div/div/div/div/div/nav/div/div[2]/div[4]/a/span</value>
      <webElementGuid>07b8a19d-15c2-45e6-bdb6-0f56e9f46ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::span[2]</value>
      <webElementGuid>365cf920-ea0d-4874-9f15-6f545baa658e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/following::span[2]</value>
      <webElementGuid>1b7bf662-aab3-4f29-9643-2a805abe6ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATASAN'])[1]/preceding::span[1]</value>
      <webElementGuid>d081fdf1-50c8-42df-89c8-a0a9a780132a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koleksi Atasan'])[1]/preceding::span[5]</value>
      <webElementGuid>b6778aac-7a49-4b3e-a9d5-75384395d401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/span</value>
      <webElementGuid>61d04f6a-89f5-435d-9ecc-27bc8edc3226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '5' or . = '5')]</value>
      <webElementGuid>c4534774-697f-42fe-a582-945f6f0f6578</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
