<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>77d0e7f5-ffe1-4e31-9907-60d145eecb76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fr-wrapper > button.fr-btn.primary.w4-f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6af0be7e-ad5e-4ba6-a2a5-deed2b6be71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr-btn primary w4-f</value>
      <webElementGuid>f000e888-e177-4722-a03c-d32be90638b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39e8432c-e9e1-448f-b9bf-7279c72fbc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>ok-button</value>
      <webElementGuid>d995ed95-46b0-41e5-a748-c8b6eae3d37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>9ae42bbe-4658-4933-9f74-a621e4fa83de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-root&quot;)/div[2]/div[@class=&quot;fr-layer-item popup-modal fr-popup-confirm open fr-no-uppercase&quot;]/section[@class=&quot;fr-popup-confirm-contents&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;inner fr-flitem fluid h-full allow-scroll&quot;]/div[@class=&quot;inner fr-flitem fluid h-full allow-scroll&quot;]/div[@class=&quot;fr-wrapper&quot;]/button[@class=&quot;fr-btn primary w4-f&quot;]</value>
      <webElementGuid>0a24502c-ef07-4130-b1c5-8fc0e69e9f0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>fc0a4633-bce7-4002-91a0-2aed38126cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-root']/div[2]/div/section/div/div/div/div/button</value>
      <webElementGuid>08bf2bf9-ab62-44da-b7d0-a7d37de2ec0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[1]/following::button[1]</value>
      <webElementGuid>f137c977-2b20-4884-b2f4-70af3ed33dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keranjang Anda telah diperbarui'])[1]/following::button[2]</value>
      <webElementGuid>3debb076-bfd1-4a06-b95d-f4cd612e4edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadikan sebagai kado'])[2]/preceding::button[1]</value>
      <webElementGuid>b6cbe9a2-bac1-40fb-827a-011c00b37577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[2]/preceding::button[1]</value>
      <webElementGuid>3c828885-2ad5-4525-b5d5-d25c8d7d6001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>c6a89659-c9a8-4f9e-a3a9-361425e9251a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/button</value>
      <webElementGuid>72c3444e-5b68-46a4-bf3c-50e8b7e9f482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>95805a3e-393b-4f34-9cc0-5178c71404a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[10]</value>
      <webElementGuid>6a8ba637-79c6-4623-b92e-114441635035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
