<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tambahkan ke wishlistWarnaUniseksXS-3XLUT Haikyu</name>
   <tag></tag>
   <elementGuidId>5578d5e1-f9bd-4761-9887-095d5c31e34d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id=''])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1a3487d6-3870-403a-a671-74b31c8c53c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr-product-card default</value>
      <webElementGuid>acc5a94b-bab3-4045-8ae8-c58ec7e80e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambahkan ke wishlistWarnaUniseksXS-3XLUT Haikyu!! Lengan PendekNewRp199.0004.8 out of 5 starsreview starreview starreview starreview starreview star(5)</value>
      <webElementGuid>372254f5-2361-46d9-a483-ca47c2d10adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;fr-layer-item content&quot;]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[@class=&quot;contained&quot;]/nav[4]/div[@class=&quot;fr-contents-card full&quot;]/div[@class=&quot;fr-image-and-product-collection&quot;]/div[@class=&quot;fr-product-grid row three-column&quot;]/div[@class=&quot;fr-grid-row&quot;]/article[@class=&quot;fr-grid-item&quot;]/a[1]/div[@class=&quot;fr-product-card default&quot;]</value>
      <webElementGuid>6d2c4cb7-2d6f-4eca-94f0-47b75f74ee5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id=''])[7]</value>
      <webElementGuid>46090127-f880-4c8a-b494-f010eba30af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/main/div/div[2]/div/div/div/nav[4]/div/div[2]/div/div/article[2]/a/div</value>
      <webElementGuid>7eacf463-3c5b-48e8-b9d3-bb7e8e03c3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(4)'])[1]/following::div[1]</value>
      <webElementGuid>5fd59d45-6bd3-4f51-8803-668b322c9019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='review star'])[5]/following::div[1]</value>
      <webElementGuid>9f5f1ede-82d5-44b8-9bf5-9cc39847e9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/article[2]/a/div</value>
      <webElementGuid>ef90920d-40d7-482e-b929-f587797abf53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tambahkan ke wishlistWarnaUniseksXS-3XLUT Haikyu!! Lengan PendekNewRp199.0004.8 out of 5 starsreview starreview starreview starreview starreview star(5)' or . = 'Tambahkan ke wishlistWarnaUniseksXS-3XLUT Haikyu!! Lengan PendekNewRp199.0004.8 out of 5 starsreview starreview starreview starreview starreview star(5)')]</value>
      <webElementGuid>5d903be4-cd76-4d4d-99af-0e4b066f161b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
