<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PRIA</name>
   <tag></tag>
   <elementGuidId>67f41e36-d9d5-4848-bae3-b43a6c571340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/main/div/div/div/div/div/nav/div/div/ul/li[2]/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ZbufY1e3fJ23MHg7axbWh.PAVGJ7j5vvoBokyUdjhu3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db9a5fa3-ddd4-4da9-b8a0-96cc4dfc8bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ZbufY1e3fJ23MHg7axbWh PAVGJ7j5vvoBokyUdjhu3</value>
      <webElementGuid>47174005-ac31-4f74-81db-f73d66203b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRIA</value>
      <webElementGuid>259e4b58-112a-46c5-9a16-4a7b8c40c98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;fr-layer-item content&quot;]/div[1]/div[1]/div[1]/main[1]/div[1]/div[@class=&quot;fr-pc-global-nav a11y-focus-section&quot;]/div[@class=&quot;sticky-outer-wrapper fr-global-nav-toolbar&quot;]/div[@class=&quot;sticky-inner-wrapper&quot;]/div[@class=&quot;fr-layer-item&quot;]/nav[@class=&quot;fr-global-nav contained _5QtkxKb0d2qo8xrZ7TTDZ&quot;]/div[@class=&quot;_34g1A1QdX1f-dwK4D1gtEI&quot;]/div[@class=&quot;_3wHXgiQc2C6hzSXloIaHBb&quot;]/ul[@class=&quot;_3rfTWmsgAVBOMnqun93Rim&quot;]/li[@class=&quot;_3PVe7lXoGboX75hQI7v94I&quot;]/a[@class=&quot;fr-global-nav-item px-s fr-link--active&quot;]/div[1]/span[@class=&quot;ZbufY1e3fJ23MHg7axbWh PAVGJ7j5vvoBokyUdjhu3&quot;]</value>
      <webElementGuid>7ed8a84f-80dc-4dd3-9f84-7e96fabdfa37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/main/div/div/div/div/div/nav/div/div/ul/li[2]/a/div/span</value>
      <webElementGuid>1ca23a97-5dd5-4597-b6d2-0eeec06cba9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='wanita'])[1]/following::span[1]</value>
      <webElementGuid>8d1862b6-aae8-4857-b78b-4e7e61772e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/following::span[3]</value>
      <webElementGuid>c2b10b41-aa5a-4552-a8ff-82b9beaa2bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak'])[1]/preceding::span[1]</value>
      <webElementGuid>0f1d07f4-1215-446b-bdd9-982f300c1998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAYI'])[1]/preceding::span[2]</value>
      <webElementGuid>dc3eb1f8-c844-4dc7-85ff-57133f0bcbe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PRIA']/parent::*</value>
      <webElementGuid>4c70c368-a99c-4c18-a829-62b3aaedcd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/span</value>
      <webElementGuid>d5b7506c-f601-4615-a021-459d3d8e5f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PRIA' or . = 'PRIA')]</value>
      <webElementGuid>a8f162f0-8780-4eb8-9140-548d45b85eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
