<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>fbc2e7ff-c022-44a3-b9cf-c2f810935d70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Masuk')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.fr-btn.primary.js-login-btn.disable-on-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81eb1f58-93c1-44bc-9cab-d40b7787ced0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8817c7fa-1218-49a5-8cc3-751a81b3c7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr-btn primary js-login-btn disable-on-submit</value>
      <webElementGuid>1af80188-518b-4324-8c49-0985e6b6cf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>login-button</value>
      <webElementGuid>dd9cbf36-1f17-426a-8481-a7635a4f5b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>09c8e063-8128-4ea3-a6ef-b9e20db11e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;fr-layer-base&quot;]/div[@class=&quot;fr-layer-item mtb-xxxl&quot;]/div[@class=&quot;bordered contained plr-m ptb-l&quot;]/div[@class=&quot;fr-flbox&quot;]/div[@class=&quot;fr-flitem fluid fr-flbox column&quot;]/div[@class=&quot;fr-wrapper&quot;]/form[@class=&quot;js-form&quot;]/div[@class=&quot;fr-wrapper w8 mb-xxs&quot;]/a[@class=&quot;fr-btn primary js-login-btn disable-on-submit&quot;]</value>
      <webElementGuid>a4c488d4-842e-40ec-b87e-0369e772d4d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk')]</value>
      <webElementGuid>5cedcb44-2749-4fdd-bf6a-d69af3846664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan privasi'])[1]/following::a[1]</value>
      <webElementGuid>c53fdda2-f258-48f3-a080-845df2800f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketentuan penggunaan'])[1]/following::a[2]</value>
      <webElementGuid>fd06fffe-3abe-463b-a856-ebe75b777eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa sandi Anda?'])[1]/preceding::a[1]</value>
      <webElementGuid>14c3e609-94f8-4e91-b997-f01cb04b6c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat akun'])[1]/preceding::a[2]</value>
      <webElementGuid>6d575787-1e36-4eb7-a52f-1d5cb1779912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>51a8fee6-3bf7-4bdf-99d3-95ec8a02fdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>96791742-24fa-404b-8903-90ade0131c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>fcdbcebd-4310-4395-b9ae-b2486bbb8081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
