<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kata sandi_password</name>
   <tag></tag>
   <elementGuidId>4eb75d31-08ee-4d5b-8fa6-5298372d7c4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc0093e2-aa5a-4163-8298-ebad85e0fb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>95df1cdf-0865-4433-ba8e-97eddf08f58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e98372e9-8814-4dc5-80ee-bcb049793e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr-textfield-input js-input-password</value>
      <webElementGuid>7bffd384-2631-455e-9562-a0147be93cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>36a25a1d-f9b0-4f93-bf26-df18e8a5f5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0a55c52a-77c0-47b5-8c69-ed3ebe53ec74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;fr-layer-base&quot;]/div[@class=&quot;fr-layer-item mtb-xxxl&quot;]/div[@class=&quot;bordered contained plr-m ptb-l&quot;]/div[@class=&quot;fr-flbox&quot;]/div[@class=&quot;fr-flitem fluid fr-flbox column&quot;]/div[@class=&quot;fr-wrapper&quot;]/form[@class=&quot;js-form&quot;]/div[@class=&quot;fr-wrapper mb-m&quot;]/div[@class=&quot;fr-textfield fr-required&quot;]/label[@class=&quot;fr-textfield-label fr-flbox column&quot;]/input[@class=&quot;fr-textfield-input js-input-password&quot;]</value>
      <webElementGuid>9a8a1b26-bd66-4d0c-95da-771a4d16f041</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>8d968f96-cc73-4eb5-a0c2-7050355c9410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>d4df2ee6-346d-4828-8370-2a86551d2990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password']</value>
      <webElementGuid>c79d8b1f-b282-4f14-b9a1-4eb78dfb35be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
